[[client]]
id = 0
connected_drone_ids = [2]

[[server]]
id = 1
connected_drone_ids = [7, 10]

[[drone]]
id = 2
connected_node_ids = [0, 9, 5]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [10, 6]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [11, 7]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [2, 8]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [3, 9]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [1, 4, 10]
pdr = 0.0

[[drone]]
id = 8
connected_node_ids = [5, 11, 12]
pdr = 0.0

[[drone]]
id = 9
connected_node_ids = [6, 2]
pdr = 0.0

[[drone]]
id = 10
connected_node_ids = [1, 7, 3]
pdr = 0.0

[[drone]]
id = 11
connected_node_ids = [8, 4]
pdr = 0.0

[[client]]
id = 12
connected_drone_ids = [8]