[[client]]
id = 0
connected_drone_ids = [6]

[[server]]
id = 1
connected_drone_ids = [8, 11]

[[drone]]
id = 2
connected_node_ids = [5, 4, 7]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [6, 5]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [2, 6, 10]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [3, 2, 12]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [4, 3, 0]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [10, 9, 2]
pdr = 0.0

[[drone]]
id = 8
connected_node_ids = [11, 10, 1]
pdr = 0.0

[[drone]]
id = 9
connected_node_ids = [7, 11]
pdr = 0.0

[[drone]]
id = 10
connected_node_ids = [8, 7, 4]
pdr = 0.0

[[drone]]
id = 11
connected_node_ids = [1, 9, 8]
pdr = 0.0

[[client]]
id = 12
connected_drone_ids = [5]